# Generated by Django 4.2.5 on 2023-09-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_company_num_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='num_employees',
        ),
    ]
